# Generated by Django 4.1.13 on 2024-07-10 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostView',
        ),
    ]
