# Generated by Django 4.1.13 on 2024-07-17 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_viewcounter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewCounter',
        ),
    ]
